name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo apt-get install -y libyaml-cpp-dev
    - name: Build with CMake
      run: |
        cmake -H. -B_build
        cmake --build _build
    - name: Test with CTest
      run: |
        cmake --build _build --target test
        ctest -C Debug
